id: P000667
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12301
  title: སྔ་འགྱུར་བཀའ་མའི་ཆོས་སྡེ་རྣམས་ཀྱི་བཞུགས་བྱང་དཀར་ཆག་རྣམ་གནོན་ཚངས་པའི་འཁོར་ལོ།
  author: ''
  volumes:
    d76180285c4b4d1ca2fb8b3f5c9a1acb:
      image_group_id: I1KG12316
      title: ''
      volume_number: 1
      total_pages: 518
