id: I36AD4413
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:49:31+00:00'
last_modified: '2022-06-07T12:35:38.087400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12301
  title: སྔ་འགྱུར་བཀའ་མའི་ཆོས་སྡེ་རྣམས་ཀྱི་བཞུགས་བྱང་དཀར་ཆག་རྣམ་གནོན་ཚངས་པའི་འཁོར་ལོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8DDE:
      image_group_id: I1KG12316
      title: ''
      total_pages: 518
      order: 1
      base_file: 8DDE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
