id: I36AD4413
legacy_id: P000667
ocr_import_info:
  bdrc_scan_id: W1KG12301
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T18:46:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:27:21.118519+00:00'
last_modified: 2022-08-31 11:27:35.918931
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12301
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12301
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་བཀའ་མའི་ཆོས་སྡེ་རྣམས་ཀྱི་བཞུགས་བྱང་དཀར་ཆག་རྣམ་གནོན་ཚངས་པའི་འཁོར་ལོ།
  author: སྨིན་གླིང་མཁན་ཆེན་ཚེ་དབང་རིག་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.916535714077077
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG12316:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12316
      total_pages: 518
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12316.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.916535714077077
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
